name: Feature Request
description: Request a new feature here
labels: ["enhancement"]
assignees:
  - Ravost99
body:
  - type: markdown
    attributes:
      value: |
        Let us know about new features you want to be added and they hopefully will be!
  - type: textarea
    id: thing
    attributes:
      label: What would you like to be added?
      description: Add multiple items if you want!
      placeholder: Actually add something useful.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Email, Discord ect
    validations:
      required: false